### ISSUE TITLE
Breathing for other cases than water/air

### ISSUE THREAD

**Issue by Cervator** [Terasology/Breathing#3]
Like discussed elsewhere :-)

The ultimate implementation might depend on the future block to prefab overhaul and a general block composition module (this gas has 50% oxygen 50% methane, works for either oxygen or methane breathers, etc)

**Comment by Cervator** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Arbitrary breathing medium system](https://trello.com/c/iSr1Dhnt/40-arbitrary-breathing-medium-system)

**Comment by jdrueckert** [comment]
This is written up in more detail on the Trello card linked above.
I'd argue that it's currently way out of scope but might be a suitable candidate for a (student) contributor project in the future as a dedicated effort.
We have it tracked on Trello, so I'll close this issue now and we can flesh out and create new issues for individual tasks related to such a project once we have somebody actually interested in implementing it.
