### ISSUE TITLE
Breathing only triggers on player movement, not plain sinking

### ISSUE THREAD

**Issue by Cervator** [Terasology/Breathing#5]
If you enter water, surface, then stop touching the movement keys and let yourself sink the breathing system doesn't trigger.

**Comment by majordwarf** [comment]
Can't recreate the issue as of now.
Modules being used: CoreSampleGameplay and Breathing.

**Comment by jdrueckert** [comment]
@Cervator did you still encounter this of late?

**Comment by Cervator** [comment]
Haven't tested for ages, but did just now and yep looks fixed 👍
